Update arch-install

diff --git a/arch-install b/arch-install
--- a/arch-install
+++ b/arch-install
@@ -735,13 +735,15 @@ net_conf_wlan()
 check_inet_conn()
 {
   title 'Network Setup > Connection Check'
-  wprintf '[+] Checking for Internet connection...'
+  wprintf '[+] Checking for Internet connection ... '
 
   if ! curl -s http://www.yahoo.com/ > $VERBOSE
   then
     err 'No Internet connection! Check your network (settings).'
     exit $FAILURE
   fi
+
+sleep "$DELAY_1"
 
 }
 
@@ -1086,6 +1088,8 @@ make_root_partition()
     sleep_clear "$DELAY_1"
   fi
 
+sleep "$DELAY_10"
+
   return $SUCCESS
 }
 
@@ -1104,10 +1108,14 @@ make_boot_partition()
   printf "\n\n"
   if [ "$BOOT_MODE" = 'uefi' ] && [ "$PART_LABEL" = 'gpt' ]
   then
-    mkfs.fat -F32 "$BOOT_PART" > $VERBOSE 2>&1 ||{ err 'Could not create filesystem'; exit $FAILURE; }
+    mkfs.fat -F32 "$BOOT_PART" > $VERBOSE 2>&1 ||
+      { err 'Could not create filesystem'; exit $FAILURE; }
   else
-    mkfs.$BOOT_FS_TYPE -F "$BOOT_PART" > $VERBOSE 2>&1 || { err 'Could not create filesystem'; exit $FAILURE; }
+    mkfs.$BOOT_FS_TYPE -F "$BOOT_PART" > $VERBOSE 2>&1 ||
+      { err 'Could not create filesystem'; exit $FAILURE; }
   fi
+
+sleep "$DELAY_10"
 
   return $SUCCESS
 }
@@ -1233,7 +1241,7 @@ install_base_packages()
   pacstrap $CHROOT base base-devel btrfs-progs linux linux-firmware linux-headers terminus-font > $VERBOSE 2>&1
   chroot $CHROOT pacman -Syy --noconfirm --overwrite='*' > $VERBOSE 2>&1
 
-  sleep "$DELAY_10"
+  sleep "$DELAY_1"
 
   return $SUCCESS
 }
@@ -1418,15 +1426,14 @@ setup_bootloader()
     if [ $LUKS = $TRUE ]
     then
       cat >> "$CHROOT/boot/loader/entries/arch.conf" << EOF
-title   BlackArch Linux
+title   Arch Linux
 linux   /vmlinuz-linux
 initrd    /initramfs-linux.img
 options   cryptdevice=UUID=$uuid:$CRYPT_ROOT root=/dev/mapper/$CRYPT_ROOT rw
 EOF
-
     else
       cat >> "$CHROOT/boot/loader/entries/arch.conf" << EOF
-title   BlackArch Linux
+title   Arch Linux
 linux   /vmlinuz-linux
 initrd    /initramfs-linux.img
 options   root=UUID=$uuid rw
@@ -1437,19 +1444,11 @@ EOF
     printf "\n\n"
 
     uuid="$(lsblk -o UUID "$ROOT_PART" | sed -n 2p)"
-
-    if [ "$INSTALL_MODE" != "$INSTALL_FULL_ISO" ]
-    then
-      chroot $CHROOT pacman -S grub --noconfirm --overwrite='*' --needed \
-        > $VERBOSE 2>&1
-    else
-      mkdir -p "$CHROOT/boot/grub"
-    fi
+    chroot $CHROOT pacman -S grub --noconfirm --overwrite='*' --needed > $VERBOSE 2>&1
 
     if [ $DUALBOOT = $TRUE ]
     then
-      chroot $CHROOT pacman -S os-prober --noconfirm --overwrite='*' --needed \
-        > $VERBOSE 2>&1
+      chroot $CHROOT pacman -S os-prober --noconfirm --overwrite='*' --needed > $VERBOSE 2>&1
     fi
 
     if [ $LUKS = $TRUE ]
@@ -1457,19 +1456,13 @@ EOF
       sed -i "s|quiet|cryptdevice=UUID=$uuid:$CRYPT_ROOT root=/dev/mapper/$CRYPT_ROOT quiet|" \
         "$CHROOT/etc/default/grub"
     fi
-    sed -i 's/Arch/BlackArch/g' "$CHROOT/etc/default/grub"
-    echo "GRUB_BACKGROUND=\"/boot/grub/splash.png\"" >> \
-      "$CHROOT/etc/default/grub"
 
     sed -i 's/#GRUB_COLOR_/GRUB_COLOR_/g' "$CHROOT/etc/default/grub"
-
     chroot $CHROOT grub-install --target=i386-pc "$HD_DEV" > $VERBOSE 2>&1
-
-    cp -f "$BI_PATH/data/boot/grub/splash.png" "$CHROOT/boot/grub/splash.png"
-
     chroot $CHROOT grub-mkconfig -o /boot/grub/grub.cfg > $VERBOSE 2>&1
-
   fi
+
+  sleep "$DELAY_10"
 
   return $SUCCESS
 }
@@ -1811,7 +1804,7 @@ setup_base_system()
   sleep_clear "$DELAY_1"
 
   setup_bootloader
-  sleep_clear "$DELAY_1"
+  sleep_clear "$DELAY_10"
 
   return $SUCCESS
 }
